name: CI
on: push
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout project
        uses: actions/checkout@v2

      - name: Install composer and dependencies
        uses: php-actions/composer@v6

      - name: PHPUnit Tests
        uses: php-actions/phpunit@v3
        env:
          XDEBUG_MODE: coverage
        with:
          bootstrap: vendor/autoload.php
          configuration: tests/phpunit/phpunit.xml
          php_extensions: xdebug
          args: tests --coverage-clover ./coverage.xml

      - name: Upload to Codecov
        uses: codecov/codecov-action@v2
        with:
          files: ./coverage.xml
          verbose: true